backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Technology Trends", value: "Technology Trends" }
          - { label: "Web Development", value: "Web Development" }
          - { label: "App Development", value: "App Development" }
          - { label: "Smart Cabling", value: "Smart Cabling" }
          - { label: "Business Growth", value: "Business Growth" }
          - { label: "Security", value: "Security" }
      - { label: "Author", name: "author", widget: "string", default: "Taziki Team" }
      - { label: "Read Time", name: "read_time", widget: "string", default: "5 min read" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
